tier_1a = [
    {"name": "Meta", "formatted_name": "meta", "scraper": ""},
    {"name": "Google", "formatted_name": "google", "scraper": ""},
    {"name": "LinkedIn", "formatted_name": "linkedin", "scraper": ""},
    {"name": "Uber", "formatted_name": "uber", "scraper": ""},
    {"name": "Salesforce", "formatted_name": "salesforce", "scraper": ""},
    {"name": "Stripe", "formatted_name": "stripe", "scraper": ""},
    {"name": "NVIDIA", "formatted_name": "nvidia", "scraper": ""},
]

tier_1b = [
    {"name": "Apple", "formatted_name": "apple", "scraper": ""},
    {"name": "Netflix", "formatted_name": "netflix", "scraper": ""},
    {"name": "OpenAI", "formatted_name": "openai", "scraper": ""},
    {"name": "Microsoft", "formatted_name": "microsoft", "scraper": ""},
    {"name": "Amazon", "formatted_name": "amazon", "scraper": ""},
]

tier_2a = [
    {"name": "Snowflake", "formatted_name": "snowflake", "scraper": ""},
    {"name": "Databricks", "formatted_name": "databricks", "scraper": ""},
    {"name": "Reddit", "formatted_name": "reddit", "scraper": ""},
    {"name": "Cloudflare", "formatted_name": "cloudflare", "scraper": ""},
    {"name": "Spotify", "formatted_name": "spotify", "scraper": ""},
    {"name": "Roblox", "formatted_name": "roblox", "scraper": ""},
    {"name": "Plaid", "formatted_name": "plaid", "scraper": ""},
    {"name": "Notion", "formatted_name": "notion", "scraper": ""},
    {"name": "Duolingo", "formatted_name": "duolingo", "scraper": ""},
    {"name": "Brex", "formatted_name": "brex", "scraper": ""},
    {"name": "DataDog", "formatted_name": "datadog", "scraper": ""},
    {"name": "Okta", "formatted_name": "okta", "scraper": ""},
    {"name": "Anthropic", "formatted_name": "anthropic", "scraper": ""},
    {"name": "Shopify", "formatted_name": "shopify", "scraper": ""},
    {"name": "Splunk", "formatted_name": "splunk", "scraper": ""},
    {"name": "Ramp", "formatted_name": "ramp", "scraper": ""},
    {"name": "CrowdStrike", "formatted_name": "crowdstrike", "scraper": ""},
    {
        "name": "Palo Alto Networks",
        "formatted_name": "palo alto networks",
        "scraper": "",
    },
    {"name": "Wiz", "formatted_name": "wiz", "scraper": ""},
    {"name": "Elastic", "formatted_name": "elastic", "scraper": ""},
    {"name": "ServiceNow", "formatted_name": "servicenow", "scraper": ""},
    {"name": "Capital One", "formatted_name": "capital one", "scraper": ""},
    {"name": "Anduril", "formatted_name": "anduril", "scraper": ""},
    {"name": "Cohere", "formatted_name": "cohere", "scraper": ""},
    {"name": "GitHub", "formatted_name": "github", "scraper": ""},
    {"name": "Affirm", "formatted_name": "affirm", "scraper": ""},
    {"name": "Splunk", "formatted_name": "splunk", "scraper": ""},
]

tier_2b = [
    {"name": "AirBnB", "formatted_name": "airbnb", "scraper": ""},
    {"name": "Atlassian", "formatted_name": "atlassian", "scraper": ""},
    {"name": "Twilio", "formatted_name": "twilio", "scraper": ""},
    {"name": "Zillow", "formatted_name": "zillow", "scraper": ""},
    {"name": "Etsy", "formatted_name": "etsy", "scraper": ""},
    {"name": "Instacart", "formatted_name": "instacart", "scraper": ""},
    {"name": "Coursera", "formatted_name": "coursera", "scraper": ""},
    {"name": "MongoDB", "formatted_name": "mongodb", "scraper": ""},
    {"name": "Squarespace", "formatted_name": "squarespace", "scraper": ""},
    {"name": "Wayfair", "formatted_name": "wayfair", "scraper": ""},
    {"name": "Fastly", "formatted_name": "fastly", "scraper": ""},
    {"name": "NetApp", "formatted_name": "netapp", "scraper": ""},
    {"name": "Shield AI", "formatted_name": "shield ai", "scraper": ""},
    {"name": "Palantir", "formatted_name": "palantir", "scraper": ""},
    {"name": "Bloomberg", "formatted_name": "bloomberg", "scraper": ""},
    {"name": "Cohesity", "formatted_name": "cohesity", "scraper": ""},
    {"name": "ThoughtSpot", "formatted_name": "thoughtspot", "scraper": ""},
    {"name": "Postman", "formatted_name": "postman", "scraper": ""},
    {"name": "Freshworks", "formatted_name": "freshworks", "scraper": ""},
    {"name": "Red Hat", "formatted_name": "red hat", "scraper": ""},
]

tier_2c = [
    {"name": "Lyft", "formatted_name": "lyft", "scraper": ""},
    {"name": "Pinterest", "formatted_name": "pinterest", "scraper": ""},
    {"name": "DoorDash", "formatted_name": "doordash", "scraper": ""},
    {"name": "Robinhood", "formatted_name": "robinhood", "scraper": ""},
    {"name": "Peloton", "formatted_name": "peloton", "scraper": ""},
    {"name": "Gusto", "formatted_name": "gusto", "scraper": ""},
    {"name": "Qualcomm", "formatted_name": "qualcomm", "scraper": ""},
    {"name": "Asana", "formatted_name": "asana", "scraper": ""},
    {"name": "GrubHub", "formatted_name": "grubhub", "scraper": ""},
    {"name": "HubSpot", "formatted_name": "hubspot", "scraper": ""},
    {"name": "Eventbrite", "formatted_name": "eventbrite", "scraper": ""},
    {"name": "Yelp", "formatted_name": "yelp", "scraper": ""},
    {"name": "IBM", "formatted_name": "ibm", "scraper": ""},
    {"name": "Gartner", "formatted_name": "gartner", "scraper": ""},
    {"name": "Riverbed", "formatted_name": "riverbed", "scraper": ""},
    {"name": "Deloitte", "formatted_name": "deloitte", "scraper": ""},
    {
        "name": "Raytheon Technologies",
        "formatted_name": "raytheon technologies",
        "scraper": "",
    },
    {"name": "General Dynamics", "formatted_name": "general dynamics", "scraper": ""},
    {"name": "L3Harris", "formatted_name": "l3harris", "scraper": ""},
    {"name": "Mattermost", "formatted_name": "mattermost", "scraper": ""},
]
