from scrapers import (
    greenhouse,  # The vast majority of companies use this
    lever,
    ashby,
    myworkdayjobs,  # Another common one
    myworkdaysite,
    icims,
    successfactors,
    nc2,
    jobvite,
    smartrecruiters,
    avature,
    netflix,
    spotify,
    uber,
    meta,
    google,
    wiz,
    apple,
    amazon,
    microsoft,
    hubspot,
    deloitte,
    qualcomm,
    linkedin,
    peloton,
    atlassian,
    github,
    ebay,
    tiktok,
)

tier_1a = [
    {
        "name": "Meta",
        "formatted_name": "meta",
        "scraper": meta,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Google",
        "formatted_name": "google",
        "scraper": google,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "LinkedIn",
        "formatted_name": "linkedin",
        "scraper": linkedin,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Uber",
        "formatted_name": "uber",
        "scraper": uber,
        "job_board_link": "https://www.uber.com/us/en/careers/list/?department=Engineering",
        "manually_verified": True,
    },
    {
        "name": "Salesforce",
        "formatted_name": "salesforce",
        "scraper": myworkdayjobs,
        "job_board_link": "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site",
        "manually_verified": True,
    },
    {
        "name": "Stripe",
        "formatted_name": "stripe",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=stripe",
        "manually_verified": True,  # Count estimated with ChatGPT's help
    },
    {
        "name": "NVIDIA",
        "formatted_name": "nvidia",
        "scraper": myworkdayjobs,
        "job_board_link": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
        "manually_verified": True,
    },
]

tier_1b = [
    {
        "name": "Apple",
        "formatted_name": "apple",
        "scraper": apple,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Netflix",
        "formatted_name": "netflix",
        "scraper": netflix,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "OpenAI",
        "formatted_name": "openai",
        "scraper": ashby,
        "job_board_link": "https://openai.com/careers/search/",
        "manually_verified": True,
    },
    {
        "name": "Microsoft",
        "formatted_name": "microsoft",
        "scraper": microsoft,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Amazon",
        "formatted_name": "amazon",
        "scraper": amazon,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "xAI",
        "formatted_name": "xai",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/xai",
        "manually_verified": True,
    },
]

tier_2a = [
    {
        "name": "Snowflake",
        "formatted_name": "snowflake",
        "scraper": ashby,
        "job_board_link": "https://careers.snowflake.com/us/en/search-results",
        "manually_verified": True,
    },
    {
        "name": "Databricks",
        "formatted_name": "databricks",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=databricks",
        "manually_verified": True,  # Count estimated with ChatGPT's help
    },
    {
        "name": "Reddit",
        "formatted_name": "reddit",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/reddit",
        "manually_verified": True,
    },
    {
        "name": "Cloudflare",
        "formatted_name": "cloudflare",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=cloudflare",
        "manually_verified": True,  # Count estimated with ChatGPT's help
    },
    {
        "name": "Spotify",
        "formatted_name": "spotify",
        "scraper": spotify,
        "job_board_link": "https://www.lifeatspotify.com/jobs",
        "manually_verified": False,  # 30 out of 76
    },
    {
        "name": "Roblox",
        "formatted_name": "roblox",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=roblox",
        "manually_verified": True,  # Count estimated with ChatGPT's help
    },
    {
        "name": "Plaid",
        "formatted_name": "plaid",
        "scraper": lever,
        "job_board_link": "https://jobs.lever.co/plaid",
        "manually_verified": True,  # Count estimated with ChatGPT's help
    },
    {
        "name": "Notion",
        "formatted_name": "notion",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/notion",
        "manually_verified": True,
    },
    {
        "name": "Duolingo",
        "formatted_name": "duolingo",
        "scraper": greenhouse,
        "job_board_link": "https://careers.duolingo.com/#careers",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Brex",
        "formatted_name": "brex",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=brex",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "DataDog",
        "formatted_name": "datadog",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=datadog",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Okta",
        "formatted_name": "okta",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=okta",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Anthropic",
        "formatted_name": "anthropic",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/anthropic",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    # Note: Shopify hires on all teams on a rolling basis; scraper would be useless
    {
        "name": "Shopify",
        "formatted_name": "shopify",
        "scraper": "",
        "job_board_link": "https://www.shopify.com/careers",
        "manually_verified": False,
    },
    {
        "name": "Splunk",
        "formatted_name": "splunk",
        "scraper": jobvite,
        "job_board_link": "https://jobs.jobvite.com/splunk-careers/jobs",
        "manually_verified": True,
    },
    {
        "name": "Ramp",
        "formatted_name": "ramp",
        "scraper": ashby,
        "job_board_link": "https://jobs.ashbyhq.com/ramp",
        "manually_verified": True,
    },
    {
        "name": "CrowdStrike",
        "formatted_name": "crowdstrike",
        "scraper": myworkdayjobs,
        "job_board_link": "https://crowdstrike.wd5.myworkdayjobs.com/crowdstrikecareers",
        "manually_verified": True,
    },
    {
        "name": "Palo Alto Networks",
        "formatted_name": "paloaltonetworks2",
        "scraper": smartrecruiters,
        "job_board_link": "https://careers.smartrecruiters.com/paloaltonetworks2",
        "manually_verified": False,  # 44 out of 1039
    },
    {
        "name": "Wiz",
        "formatted_name": "wiz",
        "scraper": wiz,
        "job_board_link": "https://www.wiz.io/careers",
        "manually_verified": False,
    },
    {
        "name": "Elastic",
        "formatted_name": "elastic",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/embed/job_board?for=elastic",
        "manually_verified": True,
    },
    {
        "name": "ServiceNow",
        "formatted_name": "servicenow",
        "scraper": smartrecruiters,
        "job_board_link": "https://careers.smartrecruiters.com/servicenow",
        "manually_verified": False,  # 30 out of ~500
    },
    {
        "name": "Capital One",
        "formatted_name": "capitalone",
        "scraper": myworkdayjobs,
        "job_board_link": "https://capitalone.wd12.myworkdayjobs.com/Capital_One",
        "manually_verified": True,
    },
    {
        "name": "Anduril Industries",
        "formatted_name": "andurilindustries",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=andurilindustries",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Cohere",
        "formatted_name": "cohere",
        "scraper": ashby,
        "job_board_link": "https://jobs.ashbyhq.com/cohere",
        "manually_verified": True,
    },
    {
        "name": "GitHub",
        "formatted_name": "githubinc",
        "scraper": github,
        "job_board_link": "https://www.github.careers/careers-home/jobs",
        "manually_verified": False,
    },
    {
        "name": "Affirm",
        "formatted_name": "affirm",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/affirm",
        "manually_verified": True,
    },
    {
        "name": "Rubrik",
        "formatted_name": "rubrik",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=rubrik",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Airtable",
        "formatted_name": "airtable",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/airtable",
        "manually_verified": True,
    },
    {
        "name": "Coinbase",
        "formatted_name": "coinbase",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=Coinbase",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Grammarly",
        "formatted_name": "grammarly",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/grammarly",
        "manually_verified": True,
    },
    {
        "name": "Retool",
        "formatted_name": "retool",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/retool",
        "manually_verified": True,
    },
    {
        "name": "Scale AI",
        "formatted_name": "scaleai",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/scaleai",
        "manually_verified": True,
    },
    {
        "name": "TikTok",
        "formatted_name": "tiktok",
        "scraper": tiktok,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Twitch",
        "formatted_name": "Twitch",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/twitch",
        "manually_verified": True,
    },
]

tier_2b = [
    {
        "name": "AirBnB",
        "formatted_name": "airbnb",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=airbnb",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Atlassian",
        "formatted_name": "apac-atlassian",
        "scraper": atlassian,
        "job_board_link": "https://www.atlassian.com/company/careers/all-jobs",
        "manually_verified": False,
    },
    {
        "name": "Twilio",
        "formatted_name": "twilio",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/twilio",
        "manually_verified": True,
    },
    {
        "name": "Zillow",
        "formatted_name": "zillow",
        "scraper": myworkdayjobs,
        "job_board_link": "https://zillow.wd5.myworkdayjobs.com/Zillow_Group_External",
        "manually_verified": True,
    },
    {
        "name": "Etsy",
        "formatted_name": "etsy",
        "scraper": myworkdayjobs,
        "job_board_link": "https://etsy.wd5.myworkdayjobs.com/Etsy_Careers",
        "manually_verified": True,
    },
    {
        "name": "Instacart",
        "formatted_name": "instacart",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=instacart",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Coursera",
        "formatted_name": "coursera",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/coursera",
        "manually_verified": True,
    },
    {
        "name": "MongoDB",
        "formatted_name": "mongodb",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=mongodb",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Squarespace",
        "formatted_name": "squarespace",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=squarespace",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Wayfair",
        "formatted_name": "wayfair",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=wayfair",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Fastly",
        "formatted_name": "fastly",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=fastly",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "NetApp",
        "formatted_name": "netapp",
        "scraper": successfactors,
        "job_board_link": "https://careers.netapp.com/search-jobs",
        "manually_verified": False,
    },
    {
        "name": "Shield AI",
        "formatted_name": "shield ai",
        "scraper": lever,
        "job_board_link": "https://jobs.lever.co/shieldai",
        "manually_verified": False,
    },
    {
        "name": "Palantir",
        "formatted_name": "palantir",
        "scraper": lever,
        "job_board_link": "https://jobs.lever.co/palantir",
        "manually_verified": True,
    },
    {
        "name": "Bloomberg",
        "formatted_name": "bloomberg",
        "scraper": avature,
        "job_board_link": "https://bloomberg.avature.net/careers/SearchJobs",
        "manually_verified": False,
    },
    {
        "name": "Cohesity",
        "formatted_name": "cohesity",
        "scraper": myworkdayjobs,
        "job_board_link": "https://cohesity.wd5.myworkdayjobs.com/Cohesity_Careers/",
        "manually_verified": True,
    },
    {
        "name": "ThoughtSpot",
        "formatted_name": "thoughtspot",
        "scraper": myworkdayjobs,
        "job_board_link": "https://thoughtspot.wd5.myworkdayjobs.com/careers",
        "manually_verified": True,
    },
    {
        "name": "Postman",
        "formatted_name": "postman",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/postman",
        "manually_verified": 67,
    },
    {
        "name": "Freshworks",
        "formatted_name": "freshworks",
        "scraper": smartrecruiters,
        "job_board_link": "https://careers.smartrecruiters.com/freshworks",
        "manually_verified": True,
    },
    {
        "name": "Red Hat",
        "formatted_name": "redhat",
        "scraper": myworkdayjobs,
        "job_board_link": "https://redhat.wd5.myworkdayjobs.com/Jobs",  # ERROR scraping redhat: Failed to fetch Workday jobs (status: None)
        "manually_verified": True,  # Works in test script but not normal script?
    },
    {
        "name": "RunPod",
        "formatted_name": "runpod",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/runpod",
        "manually_verified": True,
    },
    {
        "name": "Benchling",
        "formatted_name": "benchling",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=benchling",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Box",
        "formatted_name": "boxinc",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/boxinc",
        "manually_verified": True,
    },
    {
        "name": "Aurora Innovation",
        "formatted_name": "aurorainnovation",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=aurorainnovation",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Chime",
        "formatted_name": "chime",
        "scraper": greenhouse,
        "job_board_link": "https://careers.chime.com/en/jobs/",
        "manually_verified": True,
    },
    {
        "name": "Checkr",
        "formatted_name": "checkr",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/checkr",
        "manually_verified": True,
    },
    {
        "name": "Flexport",
        "formatted_name": "flexport",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=flexport",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Nuro",
        "formatted_name": "nuro",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=nuro",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Praetorian",
        "formatted_name": "praetorian",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/embed/job_board?for=praetorian",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Qualtrics",
        "formatted_name": "qualtrics",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=qualtrics",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "X",
        "formatted_name": "twitter",
        "scraper": myworkdayjobs,
        "job_board_link": "https://twitter.wd5.myworkdayjobs.com/X",
        "manually_verified": True,  # Works in test script but not normal script?
    },
    {
        "name": "Greenhouse",
        "formatted_name": "greenhouse",
        "scraper": greenhouse,
        "job_board_link": "https://www.greenhouse.com/careers/opportunities",
        "manually_verified": True,
    },
]

tier_2c = [
    {
        "name": "Lyft",
        "formatted_name": "lyft",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=lyft",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Pinterest",
        "formatted_name": "pinterest",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=pinterest",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "DoorDash",
        "formatted_name": "doordashusa",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/doordashusa",
        "manually_verified": True,
    },
    {
        "name": "Robinhood",
        "formatted_name": "robinhood",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=robinhood",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Peloton",
        "formatted_name": "peloton",
        "scraper": peloton,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Gusto",
        "formatted_name": "gusto",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/gusto",
        "manually_verified": True,
    },
    {
        "name": "Qualcomm",
        "formatted_name": "qualcomm",
        "scraper": qualcomm,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Asana",
        "formatted_name": "asana",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=asana",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "GrubHub",
        "formatted_name": "grubhub",
        "scraper": myworkdaysite,
        "job_board_link": "https://wd3.myworkdaysite.com/recruiting/takeaway/grubhubcareers",
        "manually_verified": False,
    },
    {
        "name": "HubSpot",
        "formatted_name": "hubspot",
        "scraper": hubspot,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Eventbrite",
        "formatted_name": "eventbriteinc",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/eventbriteinc",
        "manually_verified": True,
    },
    {
        "name": "Yelp",
        "formatted_name": "uscareers-yelp",
        "scraper": icims,
        "job_board_link": "https://uscareers-yelp.icims.com/jobs/search?ss=1",
        "manually_verified": False,
    },
    {
        "name": "IBM",
        "formatted_name": "ibm",
        "scraper": avature,
        "job_board_link": "https://ibmglobal.avature.net/en_US/careers/OpenJobs",
        "manually_verified": False,
    },
    {
        "name": "Gartner",
        "formatted_name": "gartner",
        "scraper": myworkdayjobs,
        "job_board_link": "https://gartner.wd5.myworkdayjobs.com/en-US/ext",
        "manually_verified": False,  # ERROR scraping gartner: Failed to fetch Workday jobs (status: None)
    },
    {
        "name": "Riverbed",
        "formatted_name": "careers-riverbed",
        "scraper": icims,
        "job_board_link": "https://careers-riverbed.icims.com/jobs/search?ss=1",
        "manually_verified": False,
    },
    {
        "name": "Deloitte",
        "formatted_name": "deloitte",
        "scraper": deloitte,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Raytheon Technologies",
        "formatted_name": "globalhr",
        "scraper": myworkdayjobs,
        "job_board_link": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway",
        "manually_verified": True,
    },
    {
        "name": "General Dynamics",
        "formatted_name": "gdit",
        "scraper": myworkdayjobs,
        "job_board_link": "https://gdit.wd5.myworkdayjobs.com/External_Career_Site",
        "manually_verified": True,
    },
    {
        "name": "L3Harris",
        "formatted_name": "l3harris",
        "scraper": nc2,
        "job_board_link": "https://careers.l3harris.com/en/search-jobs",
        "manually_verified": False,
    },
    {
        "name": "Mattermost",
        "formatted_name": "mattermost",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/mattermost",
        "manually_verified": True,
    },
    {
        "name": "Canonical",
        "formatted_name": "canonical",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/canonical",
        "manually_verified": True,
    },
    {
        "name": "Zest AI",
        "formatted_name": "zestai",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/zestai",
        "manually_verified": True,
    },
    {
        "name": "Chewy",
        "formatted_name": "chewy",
        "scraper": greenhouse,
        "job_board_link": "https://boards.greenhouse.io/embed/job_board?for=chewycom",
        "manually_verified": True,  # Count estimated with ChatGPT's help,
    },
    {
        "name": "Appian",
        "formatted_name": "appian",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/appian",
        "manually_verified": True,
    },
    {
        "name": "eBay",
        "formatted_name": "ebay",
        "scraper": ebay,
        "job_board_link": "",
        "manually_verified": False,
    },
    {
        "name": "Opendoor",
        "formatted_name": "opendoor",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/embed/job_board?for=opendoor",
        "manually_verified": True,
    },
    {
        "name": "Workday",
        "formatted_name": "workday",
        "scraper": myworkdayjobs,
        "job_board_link": "https://workday.wd5.myworkdayjobs.com/Workday/",
        "manually_verified": True,
    },
    {
        "name": "Verkada",
        "formatted_name": "verkada",
        "scraper": greenhouse,
        "job_board_link": "https://job-boards.greenhouse.io/verkada",
        "manually_verified": True,
    },
]
