name: Job Scraper

on:
  schedule:
    - cron: "0 */3 * * *" # Every 3 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install html5lib  # if not already included

      - name: Run scraper
        run: python3 main.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add search_results jobs_found.txt
          git commit -m "[bot] scrape - $(date)" || exit 0
          git push
